# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blog.proto',
  package='blog',
  syntax='proto3',
  serialized_options=_b('Z\r./blog/blogpb'),
  serialized_pb=_b('\n\nblog.proto\x12\x04\x62log\"E\n\x04\x42log\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tauthor_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\"-\n\x11\x43reateBlogRequest\x12\x18\n\x04\x62log\x18\x01 \x01(\x0b\x32\n.blog.Blog\".\n\x12\x43reateBlogResponse\x12\x18\n\x04\x62log\x18\x01 \x01(\x0b\x32\n.blog.Blog\"\"\n\x0fReadBlogRequest\x12\x0f\n\x07\x62log_id\x18\x01 \x01(\t\",\n\x10ReadBlogResponse\x12\x18\n\x04\x62log\x18\x01 \x01(\x0b\x32\n.blog.Blog\"-\n\x11UpdateBlogRequest\x12\x18\n\x04\x62log\x18\x01 \x01(\x0b\x32\n.blog.Blog\".\n\x12UpdateBlogResponse\x12\x18\n\x04\x62log\x18\x01 \x01(\x0b\x32\n.blog.Blog\"$\n\x11\x44\x65leteBlogRequest\x12\x0f\n\x07\x62log_id\x18\x01 \x01(\t\"%\n\x12\x44\x65leteBlogResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\t\"\x11\n\x0fListBlogRequest\",\n\x10ListBlogResponse\x12\x18\n\x04\x62log\x18\x01 \x01(\x0b\x32\n.blog.Blog2\xd2\x02\n\x0b\x42logService\x12\x41\n\nCreateBlog\x12\x17.blog.CreateBlogRequest\x1a\x18.blog.CreateBlogResponse\"\x00\x12;\n\x08ReadBlog\x12\x15.blog.ReadBlogRequest\x1a\x16.blog.ReadBlogResponse\"\x00\x12\x41\n\nUpdateBlog\x12\x17.blog.UpdateBlogRequest\x1a\x18.blog.UpdateBlogResponse\"\x00\x12\x41\n\nDeleteBlog\x12\x17.blog.DeleteBlogRequest\x1a\x18.blog.DeleteBlogResponse\"\x00\x12=\n\x08ListBlog\x12\x15.blog.ListBlogRequest\x1a\x16.blog.ListBlogResponse\"\x00\x30\x01\x42\x0fZ\r./blog/blogpbb\x06proto3')
)




_BLOG = _descriptor.Descriptor(
  name='Blog',
  full_name='blog.Blog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='blog.Blog.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='author_id', full_name='blog.Blog.author_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='blog.Blog.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='blog.Blog.content', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=89,
)


_CREATEBLOGREQUEST = _descriptor.Descriptor(
  name='CreateBlogRequest',
  full_name='blog.CreateBlogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blog', full_name='blog.CreateBlogRequest.blog', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=136,
)


_CREATEBLOGRESPONSE = _descriptor.Descriptor(
  name='CreateBlogResponse',
  full_name='blog.CreateBlogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blog', full_name='blog.CreateBlogResponse.blog', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=184,
)


_READBLOGREQUEST = _descriptor.Descriptor(
  name='ReadBlogRequest',
  full_name='blog.ReadBlogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blog_id', full_name='blog.ReadBlogRequest.blog_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=220,
)


_READBLOGRESPONSE = _descriptor.Descriptor(
  name='ReadBlogResponse',
  full_name='blog.ReadBlogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blog', full_name='blog.ReadBlogResponse.blog', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=266,
)


_UPDATEBLOGREQUEST = _descriptor.Descriptor(
  name='UpdateBlogRequest',
  full_name='blog.UpdateBlogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blog', full_name='blog.UpdateBlogRequest.blog', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=313,
)


_UPDATEBLOGRESPONSE = _descriptor.Descriptor(
  name='UpdateBlogResponse',
  full_name='blog.UpdateBlogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blog', full_name='blog.UpdateBlogResponse.blog', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=361,
)


_DELETEBLOGREQUEST = _descriptor.Descriptor(
  name='DeleteBlogRequest',
  full_name='blog.DeleteBlogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blog_id', full_name='blog.DeleteBlogRequest.blog_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=399,
)


_DELETEBLOGRESPONSE = _descriptor.Descriptor(
  name='DeleteBlogResponse',
  full_name='blog.DeleteBlogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deleted', full_name='blog.DeleteBlogResponse.deleted', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=438,
)


_LISTBLOGREQUEST = _descriptor.Descriptor(
  name='ListBlogRequest',
  full_name='blog.ListBlogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=457,
)


_LISTBLOGRESPONSE = _descriptor.Descriptor(
  name='ListBlogResponse',
  full_name='blog.ListBlogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blog', full_name='blog.ListBlogResponse.blog', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=503,
)

_CREATEBLOGREQUEST.fields_by_name['blog'].message_type = _BLOG
_CREATEBLOGRESPONSE.fields_by_name['blog'].message_type = _BLOG
_READBLOGRESPONSE.fields_by_name['blog'].message_type = _BLOG
_UPDATEBLOGREQUEST.fields_by_name['blog'].message_type = _BLOG
_UPDATEBLOGRESPONSE.fields_by_name['blog'].message_type = _BLOG
_LISTBLOGRESPONSE.fields_by_name['blog'].message_type = _BLOG
DESCRIPTOR.message_types_by_name['Blog'] = _BLOG
DESCRIPTOR.message_types_by_name['CreateBlogRequest'] = _CREATEBLOGREQUEST
DESCRIPTOR.message_types_by_name['CreateBlogResponse'] = _CREATEBLOGRESPONSE
DESCRIPTOR.message_types_by_name['ReadBlogRequest'] = _READBLOGREQUEST
DESCRIPTOR.message_types_by_name['ReadBlogResponse'] = _READBLOGRESPONSE
DESCRIPTOR.message_types_by_name['UpdateBlogRequest'] = _UPDATEBLOGREQUEST
DESCRIPTOR.message_types_by_name['UpdateBlogResponse'] = _UPDATEBLOGRESPONSE
DESCRIPTOR.message_types_by_name['DeleteBlogRequest'] = _DELETEBLOGREQUEST
DESCRIPTOR.message_types_by_name['DeleteBlogResponse'] = _DELETEBLOGRESPONSE
DESCRIPTOR.message_types_by_name['ListBlogRequest'] = _LISTBLOGREQUEST
DESCRIPTOR.message_types_by_name['ListBlogResponse'] = _LISTBLOGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Blog = _reflection.GeneratedProtocolMessageType('Blog', (_message.Message,), dict(
  DESCRIPTOR = _BLOG,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.Blog)
  ))
_sym_db.RegisterMessage(Blog)

CreateBlogRequest = _reflection.GeneratedProtocolMessageType('CreateBlogRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEBLOGREQUEST,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.CreateBlogRequest)
  ))
_sym_db.RegisterMessage(CreateBlogRequest)

CreateBlogResponse = _reflection.GeneratedProtocolMessageType('CreateBlogResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATEBLOGRESPONSE,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.CreateBlogResponse)
  ))
_sym_db.RegisterMessage(CreateBlogResponse)

ReadBlogRequest = _reflection.GeneratedProtocolMessageType('ReadBlogRequest', (_message.Message,), dict(
  DESCRIPTOR = _READBLOGREQUEST,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.ReadBlogRequest)
  ))
_sym_db.RegisterMessage(ReadBlogRequest)

ReadBlogResponse = _reflection.GeneratedProtocolMessageType('ReadBlogResponse', (_message.Message,), dict(
  DESCRIPTOR = _READBLOGRESPONSE,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.ReadBlogResponse)
  ))
_sym_db.RegisterMessage(ReadBlogResponse)

UpdateBlogRequest = _reflection.GeneratedProtocolMessageType('UpdateBlogRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEBLOGREQUEST,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.UpdateBlogRequest)
  ))
_sym_db.RegisterMessage(UpdateBlogRequest)

UpdateBlogResponse = _reflection.GeneratedProtocolMessageType('UpdateBlogResponse', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEBLOGRESPONSE,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.UpdateBlogResponse)
  ))
_sym_db.RegisterMessage(UpdateBlogResponse)

DeleteBlogRequest = _reflection.GeneratedProtocolMessageType('DeleteBlogRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEBLOGREQUEST,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.DeleteBlogRequest)
  ))
_sym_db.RegisterMessage(DeleteBlogRequest)

DeleteBlogResponse = _reflection.GeneratedProtocolMessageType('DeleteBlogResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELETEBLOGRESPONSE,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.DeleteBlogResponse)
  ))
_sym_db.RegisterMessage(DeleteBlogResponse)

ListBlogRequest = _reflection.GeneratedProtocolMessageType('ListBlogRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTBLOGREQUEST,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.ListBlogRequest)
  ))
_sym_db.RegisterMessage(ListBlogRequest)

ListBlogResponse = _reflection.GeneratedProtocolMessageType('ListBlogResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTBLOGRESPONSE,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.ListBlogResponse)
  ))
_sym_db.RegisterMessage(ListBlogResponse)


DESCRIPTOR._options = None

_BLOGSERVICE = _descriptor.ServiceDescriptor(
  name='BlogService',
  full_name='blog.BlogService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=506,
  serialized_end=844,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateBlog',
    full_name='blog.BlogService.CreateBlog',
    index=0,
    containing_service=None,
    input_type=_CREATEBLOGREQUEST,
    output_type=_CREATEBLOGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReadBlog',
    full_name='blog.BlogService.ReadBlog',
    index=1,
    containing_service=None,
    input_type=_READBLOGREQUEST,
    output_type=_READBLOGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateBlog',
    full_name='blog.BlogService.UpdateBlog',
    index=2,
    containing_service=None,
    input_type=_UPDATEBLOGREQUEST,
    output_type=_UPDATEBLOGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteBlog',
    full_name='blog.BlogService.DeleteBlog',
    index=3,
    containing_service=None,
    input_type=_DELETEBLOGREQUEST,
    output_type=_DELETEBLOGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListBlog',
    full_name='blog.BlogService.ListBlog',
    index=4,
    containing_service=None,
    input_type=_LISTBLOGREQUEST,
    output_type=_LISTBLOGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLOGSERVICE)

DESCRIPTOR.services_by_name['BlogService'] = _BLOGSERVICE

# @@protoc_insertion_point(module_scope)
